<a href="https://colab.research.google.com/github/Shantanu675/Python/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy array is much faster than simple list

In [4]:
import numpy as np
from time import process_time
python_list = [i for i in range (10000)]

start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()

print(end_time - start_time)

0.0012176170000000042


In [2]:
import numpy as np
np_array = np.array([i for i in range (10000)])

start_time = process_time()
np_array += 5
end_time = process_time()

print(end_time - start_time)

0.0002024560000000175


In [3]:
import numpy as np
n1 = np.array([1, 2, 3, 4, 5])
n1
print(n1)

[1 2 3 4 5]


In [5]:
import numpy as np
n2 = np.array([[1,2,3],[2,3,4],[3,4,5]])
n2

array([[1, 2, 3],
       [2, 3, 4],
       [3, 4, 5]])

In [6]:
import numpy as np
n3 = np.array([list[1,2,3,4,5], list[1,2]])
n3

array([list[1, 2, 3, 4, 5], list[1, 2]], dtype=object)

In [7]:
import numpy as np
li = [12, 24, 36, 48]
np.array(li)

array([12, 24, 36, 48])

In [8]:
type(n1)

numpy.ndarray

In [9]:
import numpy as np
a1 = np.zeros((1,2))
a1

array([[0., 0.]])

In [10]:
import numpy as np
a2 = np.zeros((5,5))
a2

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
import numpy as np
a3 = np.ones((3,2))
a3

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [12]:
import numpy as np
a3 = np.twos((3,2))
a3

AttributeError: module 'numpy' has no attribute 'twos'

In [13]:
import numpy as np
a4 = np.empty((5,3))

In [14]:
print(a4)

[[1.63116096e-315 0.00000000e+000 0.00000000e+000]
 [0.00000000e+000 6.67898175e-310 1.50008929e+248]
 [4.31174539e-096 9.80058441e+252 1.23971686e+224]
 [2.59032973e-144 6.06003395e+233 1.06400250e+248]
 [2.59050167e-144 5.22286946e-143 6.32404027e-322]]


In [15]:
import numpy as np
exp = np.exp([9,3])  # e^n
log = np.log(3)    # natural log to the base e
sq = np.sqrt([5, 36])
pow = np.power(3,5)
print(exp)
print(log)
print(sq)
print(pow)


[8103.08392758   20.08553692]
1.0986122886681098
[2.23606798 6.        ]
243


In [16]:
import numpy as np
n5 = np.round([1.4, 3.6, 8.9])
n6 = np.round(6.7)
n7 = np.floor(1.6)
n7_ = np.floor([9.5, 8.4, 0.3, 05.9]) # 08 = 8 in python {Not octal}
n8 = np.ceil(5.3)

print(n5)
print(n6)
print(n7)
print(n7_)
print(n8)

[1. 4. 9.]
7.0
1.0
[9. 8. 0. 5.]
6.0


In [17]:
type(a2)

numpy.ndarray

In [18]:
import numpy as np
a3 = np.full((3,2),23)
a3

array([[23, 23],
       [23, 23],
       [23, 23]])

In [19]:
# use range to form vector of values
import numpy as np
r1 = np.arange(23, 34)
r1

array([23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

In [20]:
import numpy as np
r2 = np.arange(34, 23)
r2

array([], dtype=int64)

In [21]:
import numpy as np
r3 = np.arange(10,15,0.5)
r3

array([10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5])

In [22]:
list(r3)

[np.float64(10.0),
 np.float64(10.5),
 np.float64(11.0),
 np.float64(11.5),
 np.float64(12.0),
 np.float64(12.5),
 np.float64(13.0),
 np.float64(13.5),
 np.float64(14.0),
 np.float64(14.5)]

In [23]:
for 12.5 in r3:
  print("available")

SyntaxError: cannot assign to literal (ipython-input-1801239163.py, line 1)

In [24]:
import numpy as np
k1 = np.random.randint(1,100,5) # 1 to 100 --> 5 random numbers
# random is module in numpy and randint is method available inside random module
k1

array([36,  2,  9, 28, 33])

In [25]:
# dimension of matrix
import numpy as np
k2 = np.array([[1,3,4],[4,5,6]])
k2.shape

(2, 3)

In [26]:
import numpy as np
k3 = np.array([list[1,2,3,4,5], list[1,2]])
print(k3.shape)

(2,)


In [27]:
import numpy as np
s1 = np.array([[1,2,3], [4,5,6]])
s1.shape


(2, 3)

In [28]:
s1.shape = (3,2)
print(s1)
print(s1.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [29]:
# identity matrix
w1 = np.eye(5, dtype=int)
w1

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [30]:
# array of evenly spaced values
w2 = np.linspace(10,30,7)
w2

array([10.        , 13.33333333, 16.66666667, 20.        , 23.33333333,
       26.66666667, 30.        ])

In [31]:
# another method for evenly spaced values --> with given steps
w3 = np.arange(10, 30, 7)
w3

array([10, 17, 24])

In [32]:
list1 = [1,3,6,4,8]
list2 = [10,12,16,36]

b1 = np.array(list1)
b2 = np.asarray(list2)

print(b1)
print(type(b1))
print(b2)
print(type(b2))

[1 3 6 4 8]
<class 'numpy.ndarray'>
[10 12 16 36]
<class 'numpy.ndarray'>


In [33]:
# vstack()      -----convert
import numpy as np
p1 = np.array([1,2,3,4])
p2 = np.array([6,7,8,8])
p3 = np.array([5,6,7,7]) #   --- allowed
# p4 = np.array([5,6,7,7,6]) --- not allowed
np.vstack((p1, p2, p3))

array([[1, 2, 3, 4],
       [6, 7, 8, 8],
       [5, 6, 7, 7]])

In [34]:
# hstack()
import numpy as np
p1 = np.array([1,2,3,4])
p2 = np.array([6,7,8,8])
p3 = np.array([5,6,7,7,6]) # all single dimension arrays allowed
np.hstack((p1, p2, p3))

array([1, 2, 3, 4, 6, 7, 8, 8, 5, 6, 7, 7, 6])

In [35]:
# coloumn_stack()
import numpy as np
p1 = np.array([1,2,3,4])
p2 = np.array([6,7,8,8])
p3 = np.array([5,6,7,7]) # all single dimension arrays allowed
# p4 = np.array([5,6,7,7,6]) --- not allowed
np.column_stack((p1, p2, p3))

array([[1, 6, 5],
       [2, 7, 6],
       [3, 8, 7],
       [4, 8, 7]])

In [36]:
# setdiff1d ==> setA - setB <==
import numpy as np
n1 = np.array([5,10,23,4])
n2 = np.array([3,23,56,22,5])
n = np.setdiff1d(n1, n2)
print(n)

[ 4 10]


In [37]:
# intersect1d ==> common(setA, setB) <==
import numpy as np
N = np.intersect1d(n1, n2)
print(N)

[ 5 23]


In [38]:
# sum([...enter all sets want to add])
import numpy as np
n1 = ([3,4,5])
n2 = ([4,2,6])
# n3 = ([4,5,6,8]) --- not allowed
s = np.sum([n1, n2])
print(s)

24


In [39]:
# same but here x-axis is activated
import numpy as np
n1 = ([3,4,5])
n2 = ([4,2,6])

np.sum([n1,n2], axis=1)

array([12, 12])

In [40]:
# same but here y-axis is activated
import numpy as np
n1 = ([3,4,5])
n2 = ([4,2,6])

np.sum([n1,n2], axis=0)

array([ 7,  6, 11])

In [41]:
import numpy as np
n1 = np.array([10,20,30])
n2 = np.array([12,13,14])
n1 = n1 + 1
n2 = n2 + 3
print(n1)
print(n2)
print(n1/n2)
print(n1*n2)
print(n2-2)
print(n2/3)
print(n2//3)
print(n2%3)

[11 21 31]
[15 16 17]
[0.73333333 1.3125     1.82352941]
[165 336 527]
[13 14 15]
[5.         5.33333333 5.66666667]
[5 5 5]
[0 1 2]


In [42]:
# matrix addition/subtraction
import numpy as np
m1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
m2 = np.array([[4,5,6],[7,8,9],[8,9,0]])
print(np.add(m1,m2))
print(np.subtract(m1,m2))
type(np.add(m2,m1))

[[ 5  7  9]
 [11 13 15]
 [15 17  9]]
[[-3 -3 -3]
 [-3 -3 -3]
 [-1 -1  9]]


numpy.ndarray

In [43]:
# mean, median, std ={standard deviation}, var = {varience}
import numpy as np
from scipy import stats # for mode calculation
n1 = np.array([2,6,3,2,8])
n2 = np.array([3,7,1,9,7,7])
print(np.mean(n1))
print(np.mean(n2))
print(np.median(n1))
print(np.median(n2))
print(stats.mode(n1))
print(stats.mode(n2))
print(np.std(n1))
print(np.std(n2))
print(np.var(n1))
print(np.var(n2))

4.2
5.666666666666667
3.0
7.0
ModeResult(mode=np.int64(2), count=np.int64(2))
ModeResult(mode=np.int64(7), count=np.int64(3))
2.4
2.748737083745107
5.76
7.555555555555556


In [44]:
# save with custom name provided by user
import numpy as np
n1 = np.array([10, 40, 50])
np.save("arr", n1)
n2 = np.load("arr.npy")
print(n2)

[10 40 50]
